bot:
  name: "alinaGPFBot"
  token: ${TOKEN_ENV}

logging:
  file:
    name: "./logs/app.log"
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}"
  level:
    root: info

server:
  port: 330

management:
  endpoints:
    web:
      exposure:
        include: [ 'prometheus' ]
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true


