bot:
  name: "alinaGPFBot"
  token: ${TOKEN_ENV}

ms:
  url: "http://host.docker.internal:7070"

logging:
  file:
    name: "./logs/app.log"
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}"
  level:
    root: info
